[toolchain]
anchor_version = "0.30.1"   
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs.localnet]
meme_launchpad = "6xX32V5PW4Q46qPbpHCYzFyUPXaRvPKnBsse2NimayRs"
vesting = "3HsdG1XceVgBUitEosBpP7EcwWs8yFfS3oN8Qzmv4a3P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[[test.genesis]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"  
program = "tests/dumps/raydium_cp_swap.so"

[[test.validator.account]]
address = "GThUX1Atko4tqhN2NaiTazWSeFWMuiUvfFnyJyUghFMJ"
filename = "tests/dumps/raydium_admin.json"

[[test.validator.account]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"
filename = "tests/dumps/raydium_create_pool_fee_reveiver.json"

[[test.validator.account]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
filename = "tests/dumps/amm_config_0.json"

